import { Product } from '@/shared/types/types';

export const data: Product[] = [
  {
    id: 18,
    article: 'ABA4541',
    name: 'Charming Pet Thunda Tugga',
    price: 23.58,
    color: 'ONE COLOR',
    onSale: false,
    salePrice: null,
    categoryId: 3,
    categoryName: 'Toys',
    description: 'Charming Pet Thunda Tugga',
    productType: 'OUTDOORS',
    productSizes: null,
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://cdn.shopify.com/s/files/1/0702/9579/files/outward-hound-charming-pet-thunda-tugga-bunny-14888644313190.jpg?v=1692404647',
  },
  {
    id: 19,
    article: 'ABA4541',
    name: 'Charming Pet Thunda Tugga',
    price: 23.58,
    color: 'Blue',
    onSale: false,
    salePrice: null,
    categoryId: 3,
    categoryName: 'Toys',
    description: 'Charming Pet Thunda Tugga',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'XS',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
      {
        size: 'L',
        quantity: 12,
        productStatus: 'IN STOCK',
        description: null,
      },
      {
        size: 'M',
        quantity: 12,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://cdn.shopify.com/s/files/1/0702/9579/files/outward-hound-charming-pet-thunda-tugga-bunny-14888644313190.jpg?v=1692404647',
  },
  {
    id: 20,
    article: 'ABA4541',
    name: 'Charming Pet Thunda Tugga',
    price: 23.58,
    color: 'Pink',
    onSale: false,
    salePrice: null,
    categoryId: 3,
    categoryName: 'Toys',
    description: 'Charming Pet Thunda Tugga',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'XS',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
      {
        size: 'L',
        quantity: 12,
        productStatus: 'IN STOCK',
        description: null,
      },
      {
        size: 'M',
        quantity: 12,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://cdn.shopify.com/s/files/1/0702/9579/files/outward-hound-charming-pet-thunda-tugga-bunny-14888644313190.jpg?v=1692404647',
  },
  {
    id: 21,
    article: 'ABA4541',
    name: 'Charming Pet Thunda Tugga',
    price: 23.58,
    color: 'Gray',
    onSale: false,
    salePrice: null,
    categoryId: 3,
    categoryName: 'Toys',
    description: 'Charming Pet Thunda Tugga',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'XS',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
      {
        size: 'L',
        quantity: 12,
        productStatus: 'IN STOCK',
        description: null,
      },
      {
        size: 'M',
        quantity: 12,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://cdn.shopify.com/s/files/1/0702/9579/files/outward-hound-charming-pet-thunda-tugga-bunny-14888644313190.jpg?v=1692404647',
  },
  {
    id: 16,
    article: 'ABA4537',
    name: 'Charming Pet Absurd Burds Plush Dog Toy',
    price: 16.18,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 3,
    categoryName: 'Toys',
    description: 'Charming Pet Absurd Burds Plush Dog Toy',
    productType: 'INDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://cdn.shopify.com/s/files/1/0702/9579/files/outward-hound-charming-pet-absurd-burds-plush-dog-toy-flamingo-29509589598310.png?v=1692403738',
  },
  {
    id: 49,
    article: 'ABK4565',
    name: 'Outward Hound Pawsh Donut Cuddler Bed',
    price: 84.97,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 5,
    categoryName: 'Furniture',
    description:
      "Your beloved pet deserves high-end luxury, glamour, and style. Get them only the best — beds with exquisite fabrics that provide the utmost comfort and sophisticated flair. Make sure you don't compromise when it comes to style , with Donut Cuddler Bed, you won't have to",
    productType: 'INDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/outward-hound-outward-hound-pawsh-donut-cuddler-bed-mink-29613679509606_376x489.jpg?v=1691283790',
  },
  {
    id: 59,
    article: 'ABK4576',
    name: 'Fashion Pet Buffalo Plaid Hat',
    price: 18.97,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 4,
    categoryName: 'Clothing',
    description:
      "Keep your pet's head warm and stylish this winter with Fashion Pet's Buffalo Plaid Hat. The adjustable toggle chin-strap and soft Sherpa lined ear holes give your pet maximum comfort for cold-weather walks or fun photo",
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/ethical-products-fashion-pet-buffalo-plaid-hat-29258408460390_376x489.jpg?v=1691447765',
  },
  {
    id: 28,
    article: 'ABK4542',
    name: "Li'l Pals Adjustable Dog Collar",
    price: 10.97,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 2,
    categoryName: 'Collars',
    description:
      "Give your tiny dog the perfect fit with the Li'l Pals® Adjustable Dog Collar! This dog collar is sized specifically for small dogs and puppies and has an extra narrow width. Its adjustable design ensures a secure, comfortable fit for your dog. The durable nylon material is specially processed to prevent fraying for long-lasting use. Plus, its curved, snap-lock buckle provides added comfort. Pair this adjustable dog collar with a matching Li'l Pals harness or leash for a complete look!",
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/coastal-pet-products-li-l-pals-adjustable-dog-collar-wildflower-28360782544998_376x489.jpg?v=1691409958',
  },
  {
    id: 72,
    article: 'ABK4588',
    name: 'Lacets Leather Training Lead Dog Leash',
    price: 56.57,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      'This top-notch, multi-use, genuine-leather leash is an elegant choice. Perfect for training and leisurely strolls.',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/lacets-arizona-lacets-leather-training-lead-dog-leash-29602269298790_376x489.jpg?v=1691392691',
  },
  {
    id: 45,
    article: 'ABK4561',
    name: 'FURminator De-Shedding Tool Large Dog Long Hai',
    price: 72.97,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 1,
    categoryName: 'Care',
    description:
      'Take your grooming routine into your own hands by implementing the FURminator® Ultimate Hair Reduction System™: Brush, deShed, Bathe and Maintain for grooming confidence in the comfort of your own home. Our deShedding tools, grooming tools and hair solutions offer a grooming regimen catered to any dog or cat.',
    productType: 'INDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/furminator-furminator-de-shedding-tool-large-dog-long-hair-29503791038566_376x489.jpg?v=1691450106',
  },
  {
    id: 62,
    article: 'ABK4577',
    name: 'Silver Paw 2 Piece Snow Suit',
    price: 66.27,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 4,
    categoryName: 'Clothing',
    description:
      'You and your furry pal will be able to take on the day no matter how crazy the weather gets in this incredibly practical dog snowsuit',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/silver-paw-silver-paw-2-piece-snow-suit-black-xsmall-5137448960102_376x489.jpg?v=1691177404',
  },
  {
    id: 46,
    article: 'ABK4562',
    name: 'AFP LAM Classic Lambswool Pillow Pet Bed - Brown',
    price: 59.99,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 5,
    categoryName: 'Furniture',
    description:
      'The Lambs wool Pillow Bed is the perfect bed for the dogs who think your couch is their own bed. Let your dog stretch out on his own comfortable new bed. The Lambs wool Pillow Bed offers increased comfort, durability and support for your dog. The bed provides warmth to your dog and makes them feel good and relaxed. It is available in a variety of sizes and colors',
    productType: 'INDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/all-for-paws-afp-lam-classic-lambswool-pillow-pet-bed-brown-29586970640486_376x489.png?v=1692337861',
  },
  {
    id: 73,
    article: 'ABK4589',
    name: 'Comfort Soft Reflective Wrap Adjustable Dog',
    price: 42.97,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      'The Coastal Pet Products Comfort Soft® Reflective Wrap Adjustable Dog Harness is a great choice for dogs who need a little extra comfort and security while out on walks',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/coastal-pet-products-comfort-soft-reflective-wrap-adjustable-dog-harness-xsmall-lime-28358978371686_376x489.jpg?v=1692416531',
  },
  {
    id: 11,
    article: 'AAABBB05',
    name: 'FurHaven Quilted Orthopedic Sofa',
    price: 59.99,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 5,
    categoryName: 'Furniture',
    description:
      'Curling up for a quick nap or a long night’s rest has never felt better when your sleepy pet has the FurHaven Quilted Orthopedic Sofa Cat & Dog Bed w/ Removable Cover. This high-quality bed is designed for maximum comfort with a soft.',
    productType: 'INDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://image.chewy.com/is/image/catalog/266014_MAIN._AC_SS1800_V1615845695_.jpg',
  },
  {
    id: 78,
    article: 'ABK4545',
    name: 'Silverpaw Bandana Collar, Toronto Blue Jays',
    price: 14.97,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 2,
    categoryName: 'Collars',
    description:
      'Cheer on your Toronto Blue Jays with an adorable Blue Jays bandana collar, 100% polyester for your pup and be prepared to smile! Collar is padded to add comfort when wearing.',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/silver-paw-silverpaw-bandana-collar-toronto-blue-jays-small-13668000964_376x489.jpg?v=1691175075',
  },
  {
    id: 3,
    article: 'A8574595',
    name: 'Reddy Grey Cooling Dog Bandana, X-Small/Small',
    price: 12.99,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 4,
    categoryName: 'Clothing',
    description: '- Cooling Bandana from Reddy',
    productType: 'OUTDOORS',
    productSizes: null,
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'OUT OF STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/3487838-center-10',
  },
  {
    id: 58,
    article: 'ABK4575',
    name: 'Silver Paw Hoodie With Chevron',
    price: 37.37,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 4,
    categoryName: 'Clothing',
    description:
      'Keep your dog warm and looking stylish with this warm hoodie. This piece features an interior that is lined with super soft and warm material. ',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/silver-paw-silver-paw-hoodie-with-chevron-black-small-29169982701670_376x489.jpg?v=1691176859',
  },
  {
    id: 14,
    article: 'ABA4535',
    name: 'Busy Buddy Animals Treat Dispensing Dog Toy',
    price: 12.97,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 3,
    categoryName: 'Toys',
    description: 'Busy Buddy Animals Treat Dispensing Dog Toy',
    productType: 'OUTDOORS',
    productSizes: null,
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'OUT OF STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://cdn.shopify.com/s/files/1/0702/9579/files/petsafe-busy-buddy-animals-treat-dispensing-dog-toy-3690978377830.jpg?v=1692375842',
  },
  {
    id: 61,
    article: 'ABK4578',
    name: 'Silver Paw Hooded Sweater With Chevron Pattern',
    price: 28.17,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 4,
    categoryName: 'Clothing',
    description:
      "Keep your dog warm and looking stylish with this warm knitted sweater. This piece features an interior that is lined with super soft and warm material, while the hood features a snapback closure so you're ready no matter the weather",
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/silver-paw-silver-paw-hooded-sweater-with-chevron-pattern-fuschia-xsmall-29172128579686_376x489.jpg?v=1691176862',
  },
  {
    id: 24,
    article: 'ABA4543',
    name: 'Crusha Squeezed Animal Dog Toy',
    price: 26.97,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 3,
    categoryName: 'Toys',
    description: 'Crusha Squeezed Animal Dog Toy',
    productType: 'INDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/silver-paw-crusha-squeezed-animal-dog-toy-shark-29172145586278_376x489.jpg?v=1692405553',
  },
  {
    id: 19,
    article: 'ABA4540',
    name: 'Chew Healthy Chew Dog Toy',
    price: 25.77,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 3,
    categoryName: 'Toys',
    description: "Chew'ems Healthy Chew Dog Toy",
    productType: 'OUTDOORS',
    productSizes: null,
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'OUT OF STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://cdn.shopify.com/s/files/1/0702/9579/files/hagen-chew-ems-healthy-chew-dog-toy-small-bacon-29552463609958.jpg?v=1692404830',
  },
  {
    id: 69,
    article: 'ABK4586',
    name: 'EzyDog Quick Fit Dog Harness',
    price: 44.37,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      'The EzyDog Quick Fit Harness is the perfect solution for dog owners who want the benefits of a harness with the fitting ease of a collar',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 123,
        productStatus: 'IN STOCK',
        description: null,
      },
    ],
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'IN STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/ezydog-ezydog-quick-fit-dog-harness-small-28373908324454_376x489.jpg?v=1692421390',
  },
  {
    id: 29,
    article: 'ABK4543',
    name: 'NHL Calgary Flames Adjustable Collar & Leash Set',
    price: 42.47,
    color: null,
    onSale: false,
    salePrice: null,
    categoryId: 2,
    categoryName: 'Collars',
    description: 'Size: 1" width nylon, Collar 18-24", Leash 5 feet long',
    productType: 'OUTDOORS',
    productSizes: null,
    relatedProducts: null,
    totalQuantity: 1,
    unitsSold: 0,
    productStatus: 'OUT OF STOCK',
    createdAt: 1717918937.074295,
    updatedAt: null,
    imagePath:
      'https://www.petland.ca/cdn/shop/files/silver-paw-nhl-calgary-flames-adjustable-collar-leash-set-29172081229926_376x489.jpg?v=1691334549',
  },
];
