import React from 'react';
import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { ToastContainer } from 'react-toastify';

import theme from '../shared/config/theme';
import './globals.css';
import 'react-toastify/dist/ReactToastify.min.css';

import { AppProviders } from '@/shared/config/AppProviders';
import Header from '@/modules/Header';
import Footer from '@/modules/Footer';

const lato = Lato({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  style: ['normal'],
  variable: '--font-lato',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Happy Tails',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${lato.variable} antialiased`}>
        <AppProviders>
          <MantineProvider theme={theme}>
            <Header />
            <div className='grid h-screen grid-rows-[_1fr_auto] pt-[4.625rem] lg:pt-32'>
              <main>{children}</main>
              <Footer />
            </div>

            <ToastContainer
              position='top-right'
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme='light'
            />
          </MantineProvider>
        </AppProviders>
      </body>
    </html>
  );
}
