import { Product } from '@/shared/types/types';

export const data: (Product & { uuid?: string })[] = [
  {
    id: 317,
    article: 'LUN0IJZ0',
    name: 'Textured Turtle Chew Toy for Dogs Green',
    price: 15.0,
    color: 'Green',
    onSale: true,
    salePrice: 0.0,
    categoryId: 3,
    categoryName: 'Toys',
    uuid: 'd69807bb1d724792b3ea48b3ccc10c8c',
    description:
      '<p><strong>Description:</strong></p><ul><li><p>Safe and non-toxic materials ensure your dog’s safety.</p></li><li><p>Multiple textures stimulate gums and reduce boredom.</p></li><li><p>Bright and fun design with a textured green shell and blue legs.</p></li><li><p>Perfect for small to medium dogs, promoting dental health.</p></li><li><p>Lightweight and easy to carry for both indoor and outdoor play.</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 12,
        productStatus: 'IN STOCK',
        description:
          '<p><strong>Description:</strong></p><ul><li><p>Safe and non-toxic materials ensure your dog’s safety.</p></li><li><p>Multiple textures stimulate gums and reduce boredom.</p></li><li><p>Bright and fun design with a textured green shell and blue legs.</p></li><li><p>Perfect for small to medium dogs, promoting dental health.</p></li><li><p>Lightweight and easy to carry for both indoor and outdoor play.</p></li></ul> (Green)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 12,
    unitsSold: 3,
    productStatus: 'IN STOCK',
    createdAt: 1731516359.064613,
    updatedAt: null,
    imagePath: 'https://i.imgur.com/ojSfBqt.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    uuid: '007815fb5ae94e92b8c4c7c342b92d39',
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 10,
    unitsSold: 1,
    productStatus: 'IN STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    uuid: '638e5f6d0ff6439abb1590a241604bd4',
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 10,
    unitsSold: 1,
    productStatus: 'IN STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 10,
    unitsSold: 1,
    productStatus: 'IN STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 10,
    unitsSold: 1,
    productStatus: 'IN STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 10,
    unitsSold: 1,
    productStatus: 'IN STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
  {
    id: 265,
    article: 'Z28MVJT0',
    name: 'Comfortable Dog Harness & Leash ONE COLOR',
    price: 19.99,
    color: 'ONE COLOR',
    onSale: true,
    salePrice: 0.0,
    categoryId: 6,
    categoryName: 'Leads',
    description:
      '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. </p><ul><li><p>Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. </p></li><li><p>The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. </p></li><li><p>The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p></li></ul>',
    productType: 'OUTDOORS',
    productSizes: [
      {
        size: 'ONE SIZE',
        quantity: 14,
        productStatus: 'IN STOCK',
        description:
          '<p>This comfortable and durable dog harness with a matching leash is perfect for small to medium-sized breeds. Designed with breathable mesh fabric, it ensures your pet stays cool and comfortable on walks. The adjustable straps provide a secure fit, while the sturdy metal D-ring guarantees safety during leash attachment. The vibrant blue color adds style to your outings. Ideal for daily walks, training, or adventures, this set offers both function and fashion for your furry friend!</p> (ONE COLOR)',
      },
    ],
    relatedProducts: [],
    totalQuantity: 0,
    unitsSold: 1,
    productStatus: 'OUT OF STOCK',
    createdAt: 1731495525.086767,
    updatedAt: 1732283682.007319,
    imagePath: 'https://i.imgur.com/sJiCKhF.jpeg',
  },
];
