export const products = [
  {
    id: 1,
    article: 'AAABBB001',
    name: 'Name 1',
    price: 13.5,
    categoryId: 5,
    categoryName: 'Furniture',
    description: 'Name 10 description',
    quantity: 240,
    productStatus: 'ACTIVE',
    imagePath: 'https://i.pravatar.cc',
  },
  {
    id: 2,
    article: 'AAABBB002',
    name: 'FLEX Retractable Leash Terrain Gray S (5m/20kg)',
    price: 13.5,
    categoryId: 5,
    categoryName: 'Furniture',
    description: 'Name 10 description',
    quantity: 240,
    productStatus: 'ACTIVE',
    imagePath: 'https://i.pravatar.cc',
  },
  {
    id: 3,
    article: 'AAABBB003',
    name: 'Name 3',
    price: 13.5,
    categoryId: 5,
    categoryName: 'Furniture',
    description: 'Name 10 description',
    quantity: 240,
    productStatus: 'TEMPORARILY_ABCENT',
    imagePath: 'https://i.pravatar.cc',
  },
  {
    id: 4,
    article: 'AAABBB004',
    name: 'Name 4',
    price: 13.5,
    categoryId: 5,
    categoryName: 'Furniture',
    description: 'Name 10 description',
    quantity: 240,
    productStatus: 'ACTIVE',
    imagePath: 'https://i.pravatar.cc',
  },
  {
    id: 5,
    article: 'AAABBB005',
    name: 'Name 5',
    price: 13.5,
    categoryId: 5,
    categoryName: 'Furniture',
    description: 'Name 10 description',
    quantity: 240,
    productStatus: 'ACTIVE',
    imagePath: 'https://i.pravatar.cc',
  },
  {
    id: 6,
    article: 'AAABBB006',
    name: 'Name 6',
    price: 13.5,
    categoryId: 5,
    categoryName: 'Furniture',
    description: 'Name 10 description',
    quantity: 240,
    productStatus: 'TEMPORARILY_ABCENT',
    imagePath: 'https://i.pravatar.cc',
  },
  {
    id: 7,
    article: 'AAABBB007',
    name: 'Name 7',
    price: 13.5,
    categoryId: 5,
    categoryName: 'Furniture',
    description: 'Name 10 description',
    quantity: 240,
    productStatus: 'TEMPORARILY_ABCENT',
    imagePath: 'https://i.pravatar.cc',
  },
] as const;
